name: Site workflow
on: 
  push:
    branches:
      - master


jobs:
  deploy:
    name: Jekyll deploy
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/deploy
      env:
        TEST: TESTING #${{secrets.TEST}}